### PR TITLE
Docs generation

### PR DESCRIPTION
**Pull request by bryce13950**
Make docs is all setup, and mostly ready to go. A couple things to note here...
1) The notebook benchmarks has issues running the CI. The last three cells seem to error out the make docs job with no output. At one point it said that the process was killed due to memory limitations, which is what I expect is the issue with the rest of the runs. Right now I have those three cells commented out, and I am not sure how to proceed. 
2) I changed the pre-commit commands to both fix any issues that they can fix automatically, and give more information when there is an issue. I had an issue with the format that simply said "Would Change: <filename>" without any more information. Adding `--diff` showed me that I was missing a line of white space after the imports. The `--fix` flag will also make any automatic lint changes that come up. These flags don't change the output under normal conditions, but if you have any objections to having them permanently there let me know. 
3) The docs still need to be filled in. I copied over what there was in TransformerLens, and tweaked it quite a bit. I removed all of the stuff about Transformer Lens, but the main page readme is right now simply empty. There is also a note in `toc.rst_t` that simply has an ellipsis, which needs to be filled in. Beyond that, keep an eye out for any references to TransformerLens. I think I got them all, but just be extra vigilant.

### CODE REVIEW

**Comment by bryce13950** [comment]
Also, for most of the markdown files, I cleaned them out, left some headers, and that is pretty much it. The contributing one I left as is, since it seemed mostly universal. There is some stuff in there about transformer lens, but even that seemed like it should simply be replaced with references to this project.

**Comment by alan-cooney** [comment]
Thanks for working on this!

Did you decide `mkdocs` wasn't the way to go btw? It looked a bit easier than sphinx

**Comment by bryce13950** [comment]
I can take a look at that tomorrow. It seemed like sphinx was all good to go with html generation, and parsing of notebooks. I will take a look into switching it over tomorrow after we talk.

**Comment by bryce13950** [comment]
Alright, this is running mkdocs now. Let me know if you have any questions on anything I did. Not entirely sure if this is going to be ready for full deployment. There may be some further configuration needed for the actual deployment of the site. A number of docs need to be filled in a bit. The build also automatically generates a folder in `docs/contents` named `reference`, which is the auto generated source code docs. I am treating that as a build artifact, and thus it is being ignored for the purposes of version control. If we want to do any customization on that, then we probably need to include that, and customize the docs after generation. I think what is being generated is fine though.

You can view it locally by running `poetry install --with=docs` and then `poe docs-hot-reload`

**Review by alan-cooney — DISMISSED** [review]
This looks great! Thanks for adding

**Pull request merged**
