### PR TITLE
Refactored resizing code to make more transparent

### PR DESCRIPTION
**Pull request by Baidicoot**
It makes sense to split off the activation resizing code from the `ActivationStore` instances and specify resizing in the generation code. For instance, when generating from e.g. `blocks.x.attn.hook_z` normally, the old behavior was to treat each head as a new batch, instead of concatenating the head activations.

With the new/proposed behavior, a resizing method is specified when the generation method is called, which is by default the old resizing method.

### CODE REVIEW

**Comment by alan-cooney** [comment]
Just to say - makes sense thanks for working on this. I'll switch to draft and then feel free to tag me when it's ready for review. Also running the cli command `poe lint` will probably sort the linting issues automatically.

**Comment by Baidicoot** [comment]
@alan-cooney should be ready for review now as it's passing the tests; sorry about failing to make it check earlier, I'm quite unfamiliar with poe/github checks.

**Comment by Baidicoot** [comment]
Hi @alan-cooney, I've updated this PR for the current (22/11/23) codebase, now activation stores only deal with `InputOutputActivationBatch`es etc, while all reshaping code lives with the hook functionality, as should probably be the case.

Possibly TODO is to add tests for the reshaping methods.

**Comment by alan-cooney** [comment]
Merged into #160

**Pull request closed without merging**
